### ISSUE TITLE
A decent PHP extension

### ISSUE THREAD

**Issue by szepeviktor** [matthiasnoback/recipes-for-decoupling-phpstan-rules#1]
... must satisfy PHPStan Level max rules.

```php
/**
 * @implements \PHPStan\Rules\Rule<\PhpParser\Node\Expr\MethodCall>
 */
final class UseEmailValidatorRule implements Rule
{
```

@matthiasnoback Would you welcome a PR?

**Comment by matthiasnoback** [comment]
Well, this one could be useful. I realize now that I didn't run PHPStan on the rules. Would be a good improvement for the book too.
