### ISSUE TITLE
Viktor's default CI

### ISSUE THREAD

**Issue by szepeviktor** [matthiasnoback/recipes-for-decoupling-phpstan-rules#6]
Would you welcome a [CI like this](https://github.com/szepeviktor/debian-server-tools/blob/master/webserver/Continuous-integration-Continuous-delivery.yml)?

[![kép](https://user-images.githubusercontent.com/952007/177055625-8f657fc6-02b1-40fa-94c8-5d61922f49c0.png)](https://github.com/szepeviktor/debian-server-tools/blob/master/webserver/Continuous-integration-Continuous-delivery.yml)

**Comment by matthiasnoback** [comment]
Although it looks good, this is too much for a simple project like this.
